import { GiLovers } from "react-icons/gi";

export const menuCategories = [
  {
    id: 1116,
    parentId: 910,
    name: "Carti de dragoste",
    url: "romane-de-dragoste-romantice",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1055,
    parentId: 910,
    name: "Dezvoltare personala",
    url: "dezvoltare-personala",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1058,
    parentId: 910,
    name: "Carti pentru copii",
    url: "pentru-copii",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1117,
    parentId: 910,
    name: "Young Adult",
    url: "young-adults-pentru-adolescenti",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1125,
    parentId: 910,
    name: "Carti fictiune",
    url: "fictiune",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1059,
    parentId: 910,
    name: "Nutritie & Sanatate",
    url: "de-nutritie-sanatate",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1121,
    parentId: 910,
    name: "Thriller, mister si suspans",
    url: "thriller-mister-suspans",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1057,
    parentId: 910,
    name: "Memorii, biografii si jurnale",
    url: "memorii-biografii-jurnale-celebre",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1054,
    parentId: 910,
    name: "Beletristica",
    url: "beletristica",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1062,
    parentId: 910,
    name: "Religie",
    url: "religie",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1061,
    parentId: 910,
    name: "Cresterea copilului",
    url: "parenting-cresterea-copilului",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1165,
    parentId: 910,
    name: "Afaceri si investitii",
    url: "antreprenoriat-afaceri-investitii",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1066,
    parentId: 910,
    name: "Istorie",
    url: "istorie",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1068,
    parentId: 910,
    name: "Gastronomie",
    url: "gastronomie",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1063,
    parentId: 910,
    name: "Spiritualitate si ezoterism",
    url: "spiritualitate-si-ezoterism",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1067,
    parentId: 910,
    name: "Manuale si auxiliare scolare",
    url: "auxiliare-manuale-scolare",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1351,
    parentId: 910,
    name: "Non-fictiune",
    url: "non-fictiune",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1352,
    parentId: 910,
    name: "Cărți în limba engleză",
    url: "carti-in-limba-engleza",
    icon: <GiLovers />,
    subCategories: null,
  },
  {
    id: 1297,
    parentId: 910,
    name: "Carti Sociologie",
    url: "sociologie-stiinte-umaniste",
    icon: <GiLovers />,
    subCategories: null,
  },
];
