const content = {
  btn_forgot_Password: "Recuperează parola",
  enter_the_account: "Intră în cont",
  add_to_cart: "Adaugă în coș",
  add_to_favorite: "Adaugă la favorite",
  remove_to_favorite: "Șterge de la favorite",
  go_to_login: "Mergi la pagina de login",
  cancel: "Anulează",
  continue: "Continuă",
  create_account: "Crează cont",
  create_account_title: "Creare cont nou pe Bookoutlet.ro",
  create_account_subtitle: "Completează datele noului tău cont Bookoutlet.",
  login_title: "Login pe Bookoutlet",
  login_subtitle: "Introdu credențialele pentru a te conecta",
  or: "sau",
  continue_with_google: "Continuă cu Google",
  no_account: "Nu ai cont? Crează unul aici",
  login_with: "Loghează-te cu",
  forgot_password: "Ai uitat parola?",
  forgot_password_subtitle:
    "Completează câmpurile de mai jos pentru a accesa contul tău din aplicația BookOutlet",
  newsletter_personal_page: "Vreau să primesc newsletterul BookOutlet",
  save: "Salvează",
  welcome: "Bine ai venit,",
  products: "produse",
  empty_list_favorite: "Nu ai produse favorite.",
  favorite_title: "Favorite",
  my_vouchers: "Voucherele mele",
  vouchers: "vouchere",
  my_orders: "Comenzile mele",
  orders: "comenzi",
  empty_orders: "Nu ai comenzi.",
};

export default content;
