const content = {
  btn_forgot_Password: "Recuperează parola",
  enter_the_account: "Intră în cont",
  add_to_cart: "Adaugă în coș",
  add_to_favorite: "Adaugă la favorite",
  remove_to_favorite: "Șterge de la favorite",
  go_to_login: "Mergi la pagina de login",
  cancel: "Anulează",
  continue: "Continuă",
  create_account: "Crează cont",
  create_account_title: "Creare cont nou pe Bookoutlet.ro",
  create_account_subtitle: "Completează datele noului tău cont Bookoutlet.",
  login: "Loghează-te",
  login_title: "Login pe Bookoutlet",
  login_subtitle: "Introdu credențialele pentru a te conecta",
  noUserAddToFavorite:
    "Pentru a putea adauga la favorite o carte trebuie sa intri in contul tau BookOutlet",
  noUserAddReview:
    "Pentru a putea lasa o recenzie trebuie sa intri in contul tau Bookoutlet.",
  or: "sau",
  continue_with_google: "Continuă cu Google",
  no_account: "Nu ai cont? Crează unul aici",
  login_with: "Loghează-te cu",
  forgot_password: "Ai uitat parola?",
  forgot_password_subtitle:
    "Completează câmpurile de mai jos pentru a accesa contul tău din aplicația BookOutlet",
  newsletter_personal_page: "Vreau să primesc newsletterul BookOutlet",
  save: "Salvează",
  welcome: "Bine ai venit,",
  products: "produse",
  empty_list_favorite: "Nu ai produse favorite.",
  favorite_title: "Favorite",
  my_vouchers: "Voucherele mele",
  vouchers: "vouchere",
  my_orders: "Comenzile mele",
  orders: "comenzi",
  empty_orders: "Nu ai comenzi.",
  phoneOrder: "Comandă prin telefon",
  numberOrder: "0712345678",
  storeProgram: "L-V 9:30 - 17:30",
  shippingRomania: "Livrare în România",
  shippingDays: "1-3 zile lucrătoare",
  shippingEasybox: "Ridicare din EasyBox",
  numberPeople: "persoane se uită la acest produs.",
  hurry: "Grăbește-te! La acest produs, stocurile sunt limitate.",
  currency: "Lei",
  productCost: "Cost produse:",
  deliveryCost: "Cost livrare:",
  processingCost: "Cost procesare:",
  total: "Total:",
  orderSummary: "Sumar comandă",
  subtotal: "Subtotal:",
};

export default content;
